---
- name: remove unused ntp packages
  package:
    name: "{{ systemd_timesyncd_remove_packages }}"
    state: absent

- name: install packages
  package:
    name: "{{ systemd_timesyncd_packages }}"
    state: present
