---
- name: ensure systemd-timesync config directory exists
  file:
    path: /etc/systemd/timesyncd.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create systemd-timesyncd configuration file
  template:
    src: etc/systemd/timesyncd.conf.d/timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf.d/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart systemd-timesyncd

- name: start and enable systemd-timesyncd
  systemd:
    name: systemd-timesyncd.service
    state: started
    enabled: yes
