---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: systemdtimesyncdcentos8
    image: registry.gitlab.com/dvonessen/docker-molecule-nonroot/centos:8-systemd
    command: /usr/lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: systemdtimesyncddebian10
    image: registry.gitlab.com/dvonessen/docker-molecule-nonroot/debian:10-systemd
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: systemdtimesyncdubuntu2004
    image: registry.gitlab.com/dvonessen/docker-molecule-nonroot/ubuntu:20.04-systemd
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      interpreter_python: auto_silent
lint: |
  set -e
  yamllint -c .yamllint .
  flake8
  ansible-lint
